---
languages:
  Ruby: true
engines:
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: false
    exclude_fingerprints:
    - 97ef33d0516489c514d21af9b76b8b98
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- lib/frilans_finans_api/spec/**/*
- lib/json_api_helpers/spec/**/*
- lib/welcome_app/spec/**/*
- lib/seeds/dev
- lib/migrate_data/migrate_translations.rb
- lib/migrate_data/user_language_to_system_language.rb
- vendor/**/*
