routes:
  base_url: 'https://app.justarrived.se/'
  reset_password: 'reset-password/%{token}'
  login: 'login'
  register: 'register'
  magic_login_link: 'user/magic-login/%{token}'
  job: 'job/%{id}'
  jobs: 'jobs/1' # 1 is the page number (and is needed, will 404 otherwise)
  faqs: 'faq'
  job_user_for_company: 'company/job/%{job_id}/candidate/%{job_user_id}'
  job_users: 'company/job/%{job_id}/candidates'
  job_user: 'job/%{job_id}'
  user_edit: 'user'
  user_basic_data_edit: '/basic-user-data'
  chat: 'support-chat?message_id=%{message_id}'
  unsubscribe: 'subscriptions/%{subscriber_id}'
