# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb528b02d2b854fd61ff4fc0f26b7e72c7d9c4a8b4bfc8a6a415b861f0a3046d654e026a5a0ce420925626e0d22209d0a671c467acb34a4cbcac12a054aadb03

test:
  secret_key_base: 2e638bc008286c2cecd9771361db29c169289bd3ed69a74d683375014af30ea48ce56b3e2cc14269a55da3c1e312c3a5085e5c654e122663a4b862c37b19e3af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
